### ISSUE TITLE
[Feature Request] Add an option to see wattage 

### ISSUE THREAD

**Issue by Tareq4322** [Solarphlare/BatteryTile#11]
The title already sums up the request that I've made. I would really appreciate it if you could add that option. Keep up the good work!!

**Comment by Solarphlare** [comment]
Sounds like something that shouldn't be hard to do. I'll try and get this added in sometime soon!

**Comment by Tareq4322** [comment]
Any update on this issue?

**Comment by Solarphlare** [comment]
Hey there—sorry for the long delay. School and other things have had me wrapped up for a while.

Regarding the feature, I've already got a [commit](https://github.com/CominAtYou/BatteryTile/commit/580acd10efc29507caad0f5f08a29b5989e396f0) for it, I just haven't had the time to get a few other things worked on (mostly localisation) before I'm able to publish a new release. I should have some time soon to get that done, and then I'll be able to publish a new release with the feature.

**Comment by Solarphlare** [comment]
Added in [v1.7.0](https://github.com/CominAtYou/BatteryTile/releases/tag/v1.7.0).
