### ISSUE TITLE
Feature add

### ISSUE THREAD

**Issue by Tareq4322** [Solarphlare/BatteryTile#13]
Please add an option to see charge time estimate With other components. Now we have leave the text field blank if we want to see the change time estimate along side battery percentage but I want to see current battery wattage and change time together, it would be really helpful if you could add an option see charge time estimate with other components.

**Comment by Solarphlare** [comment]
Sure thing! No idea why I didn't add that earlier.

**Comment by Tareq4322** [comment]
If possible can you also include the battery charge remaining estimate ? 
![Screenshot_20241020-110435_Settings](https://github.com/user-attachments/assets/c06ee488-5cba-44e7-9e08-56147721da81)

**Comment by Solarphlare** [comment]
There’s no API that allows apps to get that information, so I’m afraid that’s not possible.

**Comment by Solarphlare** [comment]
Added in [v1.8.0](https://github.com/CominAtYou/BatteryTile/releases/tag/v1.8.0).
