### ISSUE TITLE
Tile subtitle is hidden

### ISSUE THREAD

**Issue by RamPawar7** [Solarphlare/BatteryTile#3]
On my Samsung phone with Android 10 and OneUI 2.0, the battery percentage and time until full isn't shown like that in the your screenshots.

How it looks on my phone -
![20230527_111632](https://github.com/CominAtYou/BatteryTile/assets/96973076/aa4660c7-d211-4834-a0ba-99f56f139777)

This is the case for both: on battery and during charging.

This issue also occurs with [this](https://play.google.com/store/apps/details?id=net.xnano.android.batteryquicktile) battery tile app.
It's screenshot-
![20230527_111727](https://github.com/CominAtYou/BatteryTile/assets/96973076/aa1c1721-49ff-401e-b574-df93c3e5afd7)

Can you add options to control what bits of information to show and where to show it (in the main title or the subtitle of the tile)?

Also, will you add more features to your app like those in the above mentioned app? If yes, then I will make another issue listings the features I would like your app to have. Thank you.

**Comment by Solarphlare** [comment]
I can certainly add those options. I'm also open to whatever ideas you've got, so feel free to open another issue detailing what you'd like to see added.

**Comment by Solarphlare** [comment]
I've added this in [v1.3.1](https://github.com/CominAtYou/BatteryTile/releases/tag/v1.3.1).
