### ISSUE TITLE
Multiple feature requests

### ISSUE THREAD

**Issue by RamPawar7** [Solarphlare/BatteryTile#4]
Here are some features and changes I would like to be added in this app-

1. Add options to show battery teprature, charging/discharging current, voltage, power (watt) in the title (at least add the first two if not all). Remove battery percentage as it is already shown in the status bar.
2. Add options to show the tile as OFF by default. May be add another option to show it as ON only when charging.
3. May be change the icon to two tone icon like in this image ![20230527_131315](https://github.com/CominAtYou/BatteryTile/assets/96973076/e068e2ea-a2f2-4d57-966c-e6911cad97d1)

4. Different icons for while charging and while on battery, like that in the above image but instead of the lighting bolt, show two pin AC plug icon while AC charging and USB icon while usb charging.

**Comment by Solarphlare** [comment]
This has been added in [v1.4.0](https://github.com/CominAtYou/BatteryTile/releases/tag/v1.4.0).

**Comment by RamPawar7** [comment]
> This has been added in [v1.4.0](https://github.com/CominAtYou/BatteryTile/releases/tag/v1.4.0).

That's great! I like how you made it highly customizable. Thank you!
