### ISSUE TITLE
[FEATURE REQUEST] Add Shizuku or Root mode

### ISSUE THREAD

**Issue by HarriBuh** [Solarphlare/BatteryTile#7]
Granting the app its necessary permissions via ADB may not be that difficult in reality, I prefer on board software and mechanics to to this job much more, though.
Shizuku could he the perfect candidate here, as it does not require root, while it should do the same as ADB - I'm no expert or programmer, I just use it on a daily basis and recognised possible similarities here.

Is it possible?

**Comment by Solarphlare** [comment]
It's definitely possible to add to the app, but the Shizuku API is rather cumbersome and difficult to implement, which is why I decided to pass on it at first. But given that I've had multiple people mention Shizuku as of now, I'll try and see if I can get it added into the app.

**Comment by Solarphlare** [comment]
This unfortunately doesn't look like something I'll be able to do - really sorry about that.
