### ISSUE TITLE
Did you know

### ISSUE THREAD

**Issue by kaoneko** [Solarphlare/BatteryTile#9]
> The "Battery Saver" tile in Android 12 in below, when long-pressed, would open the battery settings page in Android Settings. With the introduction of Android 13, it no longer presents the battery settings page. Instead, it now opens the Battery Saver settings, removing this very useful shortcut. This app aims to restore said functionality with a custom Quick Settings tile.

Did you know tapping the battery percentage in Quick Settings takes you straight to the battery settings page? I think this was re-introduced in Android 13. Feels like the whole reason to make your app was based on not knowing this 😅

**Comment by Wrx95Pro** [comment]
Until it's not. For me on Pixel with stock AOSP-like ROM there is no such feature.

**Comment by kaoneko** [comment]
Wait, it's a LineageOS thing then? Until a few months ago I was running the stock Android 13 ROM on my Pixel, thought that had it too, I learned about it on Reddit. Now I'm on LineageOS which definitely has it.

Just to be sure: it only works in quick settings, not in the notification shade.

**Comment by Wrx95Pro** [comment]
It must be custom, as on stock 14 (QPR3 latest beta) there are only Clock shortcut and Network & Internet when tapping on carrier name. I miss the calendar shortcut from 11.

**Comment by Solarphlare** [comment]
I'm thinking (as the others have said) that this likely is something that's only on Lineage. I can confirm that I don't have this feature on my Pixel or my Galaxy phone.

**Comment by kaoneko** [comment]
Interesting, thanks for the replies. Strangely enough, a while ago I could also tap the date to open Calendar, now it just opens the clock (same as tapping the time). I was running Pixel Xpert (on both stock and LOS) until recently, maybe that also adds this kind of functionality...
